version: "3.7"
services:
  ang23-app:
    build: .
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: ./
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
